### ISSUE TITLE
test the model on NWPU VHR dataset

### ISSUE THREAD

**Issue by TerrafYassin** [Shank2358/NPMMR-Det#17]
did you test you model on NWPU VHR dataset , because i dont have enought ressources to train my model on DOTA or DIOR dataset , 
if Yes can you give me please dataset split used and the accuracy obtained to compare it with what i obtained , thank you.

**Comment by Shank2358** [comment]
Sorry, we have not performed experiments on this dataset because it is too small. I have converted their labels as follows, maybe you can try to train them. Thanks.

[trainval.txt](https://github.com/Shank2358/NPMMR-Det/files/9552862/trainval.txt)

[val.txt](https://github.com/Shank2358/NPMMR-Det/files/9552863/val.txt)

[test.txt](https://github.com/Shank2358/NPMMR-Det/files/9552864/test.txt)

[train.txt](https://github.com/Shank2358/NPMMR-Det/files/9552865/train.txt)
