### ISSUE TITLE
Paper question

### ISSUE THREAD

**Issue by TerrafYassin** [Shank2358/NPMMR-Det#21]
After reading some papers in objects detection from remote sensing images i found that in the Neck part to propagate context information of the object dilated convolution is used and to propagate semantic information deformable convolution is used , but in your paper you used deformable convolution to extract context information in buttom up pathway and dilated convolution to extract semantic information top down pathway, can you explain this point to me?

**Comment by Shank2358** [comment]
The purpose of using DCN is to align the classification and localization features instead of extracting contextual features. Because the features of the localization and classification branches focus on different spatially sensitive regions, we hope to use deformable convolution to align the features of different tasks in the head components. The use and discussion of this part of the work are sketchy. This issue is further studied and discussed in our follow-up work. https://arxiv.org/abs/2209.02200

The purpose of using dilated convolution is to expand the receptive field. The scale differences of objects in remote sensing images are very large, which leads to the fact that the receptive fields of different branches of FPN cannot adapt to such scale differences of objects. Therefore, dilated convolutions with different expansion rates are designed to extract features through filters of different window sizes and fuse these features to alleviate the above problems.

Thank you.

**Comment by Shank2358** [comment]
> After reading some papers in objects detection from remote sensing images i found that in the Neck part to propagate context information of the object dilated convolution is used and to propagate semantic information deformable convolution is used , but in your paper you used deformable convolution to extract context information in buttom up pathway and dilated convolution to extract semantic information top down pathway, can you explain this point to me?

The purpose of using DCN is to align the classification and localization features instead of extracting contextual features. Because the features of the localization and classification branches focus on different spatially sensitive regions, we hope to use deformable convolution to align the features of different tasks in the head components. The use and discussion of this part of the work are sketchy. This issue is further studied and discussed in our follow-up work. https://arxiv.org/abs/2209.02200

The purpose of using dilated convolution is to expand the receptive field. The scale differences of objects in remote sensing images are very large, which leads to the fact that the receptive fields of different branches of FPN cannot adapt to such scale differences of objects. Therefore, dilated convolutions with different expansion rates are designed to extract features through filters of different window sizes and fuse these features to alleviate the above problems.

Thank you.

**Comment by Ismaildata** [comment]
Thank you , but sir in which part of  your framwerok you extract contextual information  ?

**Comment by Ismaildata** [comment]
New Feature Fusion Pathway of MSR-FPN: As shown
in Fig. 5(b), in order to propagate the high-resolution features
from the shallower layers to the deeper layers, a bottom-up
branch (green blocks and their connected path) is added, which
allows each branch to fully fuse multiscale context features.
in your paper you mentionned you said that you extract multiscale context features you used DCN v1 and to align classification and localisation features you used DCN v2.
my question is why did you used DCN v1 to extract context information in the Neck ?

**Comment by Shank2358** [comment]
> New Feature Fusion Pathway of MSR-FPN: As shown in Fig. 5(b), in order to propagate the high-resolution features from the shallower layers to the deeper layers, a bottom-up branch (green blocks and their connected path) is added, which allows each branch to fully fuse multiscale context features. in your paper you mentionned you said that you extract multiscale context features you used DCN v1 and to align classification and localisation features you used DCN v2. my question is why did you used DCN v1 to extract context information in the Neck ?

OK. I see. Since the downsampling process will lead to the offset of feature positions, we use DCN for downsampling and hope to correct this offset. Thanks.
![image](https://user-images.githubusercontent.com/33946139/191016999-c181a1ae-8fd0-4c2b-87f4-158bd79bb9bb.png)
