### ISSUE TITLE
Paper question

### ISSUE THREAD

**Issue by TerrafYassin** [Shank2358/NPMMR-Det#22]
Can you briefly explain to me these parameters of Non local attention mechanism in terms of the information it gives, i mean what is information obtained by Phi , G and Théta .
![image](https://user-images.githubusercontent.com/37477283/190607021-d5f6355a-c70a-46f4-8fdc-c0c511ac7358.png)
Thank you .

**Comment by Shank2358** [comment]
> Can you briefly explain to me these parameters of Non local attention mechanism in terms of the information it gives, i mean what is information obtained by Phi , G and Théta . ![image](https://user-images.githubusercontent.com/37477283/190607021-d5f6355a-c70a-46f4-8fdc-c0c511ac7358.png) Thank you .

I drew a diagram that might make the process easier to understand.
![image](https://user-images.githubusercontent.com/33946139/190889966-ad8b0169-d4c5-4059-99cc-46f715b22d77.png)
First, perform a 1×1 convolution with learnable weights on the features X and X_{NP} respectively, and then expand the obtained tensor into one column (vectorization), which contains the features of each spatial position at different scales, namely Phi, G, and Théta. The process of multiplying Phi, G, and Théta is to make each spatial location feature cross-correlated with other spatial locations to obtain the response of feature correlation.

**Comment by Ismaildata** [comment]
But why we need to learn   weights on the features X and Xnp and my second question in wich part you did correlation between channel-wise , because you mentionned in your paper you used spatial and channel correlation to highlight important features.

**Comment by Ismaildata** [comment]
also sir cross correlation is calculated between query and key not query and values as you mentionned above no ?

**Comment by Shank2358** [comment]
> But why we need to learn weights on the features X and Xnp and my second question in wich part you did correlation between channel-wise , because you mentionned in your paper you used spatial and channel correlation to highlight important features.

Hi. The cross-correlation between features X and Xnp  represents the correlation between the feature at each spatial location of the feature map and the features of other locations (including its multi-scale neighborhood fusion features). The schematic above shows only the two-dimensional case, in fact it should be an expansion of a three-dimensional tensor. So the correlation is the correlation of each space and channel location. In the upper left paragraph of the fifth page of the paper, we mentioned that according to the commutative law of multiplication, we first calculate the last two items instead of Q×K in self attention. That is, (QK)V=Q(KV) in this case (using the dot-product form).
![image](https://user-images.githubusercontent.com/33946139/191016552-e6be4013-4c92-47cb-b3cf-0ed824509db5.png)

**Comment by Shank2358** [comment]
> But why we need to learn weights on the features X and Xnp and my second question in wich part you did correlation between channel-wise , because you mentionned in your paper you used spatial and channel correlation to highlight important features.

unfold like this
![image](https://user-images.githubusercontent.com/33946139/191018123-570c5943-49ab-4eca-9c92-e929859ae84f.png)

**Comment by TerrafYassin** [comment]
![image](https://user-images.githubusercontent.com/37477283/191042598-6edc4ed2-22b3-40e8-836d-ff55936a71ff.png)
in your paper you u calcuated cross correlation between K and Query and then you multiply by V

**Comment by Shank2358** [comment]
> ![image](https://user-images.githubusercontent.com/37477283/191042598-6edc4ed2-22b3-40e8-836d-ff55936a71ff.png) in your paper you u calcuated cross correlation between K and Query and then you multiply by V

Thank you. I am sorry for the inconsistency with the illustration. In the illustration, we have drawn it in the order of self attention. However, in the equations in the subsequent part of the paper and in our codes, it has explained that the last two items are calculated first and then the former item is calculated. 
See this part of the code:  
![image](https://user-images.githubusercontent.com/33946139/191933613-bb24b62a-a5ba-4126-a488-e398a5ed7ee9.png)  
In fact, the final calculation result of the two schemes is the same because it conforms to the multiplicative associative law and does not affect the performance.
